kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: t8c-operator
subjects:
- kind: ServiceAccount
  name: t8c-operator
  namespace: lemur
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
